### ISSUE TITLE
bugs QA

### ISSUE THREAD

**Issue by jairdean** [JCastillo92/Mercado_Ambiental#7]
1) problema cuando LA BASE ESTA VACIA DE imgs
2016-07-17T12:44:29.067-0500|Info: Select id_prod_pj from tb_pujas where principal='true';
2016-07-17T12:44:29.102-0500|Info: null
2016-07-17T12:44:29.102-0500|Info: Select mes from tb_tiempo where id_puja=;
2016-07-17T12:44:29.103-0500|Info: null
2016-07-17T12:44:29.103-0500|Info: -------------------2--------------
2016-07-17T12:44:29.103-0500|Info: null
2016-07-17T12:44:29.104-0500|Info: null
2016-07-17T12:44:29.104-0500|Info: null
2016-07-17T12:44:29.140-0500|Warning: StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
java.lang.NullPointerException
    at metodos.Cls_General.carruseles(Cls_General.java:411)
    at org.apache.jsp.index_jsp._jspService(index_jsp.java:80)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)

**Comment by jairdean** [comment]
desactivar campo y boton buscar en INDEX.

**Comment by jairdean** [comment]
quitar el icono o logo de universidad en cada titulo de trueque en el INDEX

**Comment by jairdean** [comment]
mejorar footer INDEX

**Comment by jairdean** [comment]
mejorar el tamano de la informcion en index y ponerle SOLO UN  <br>entre el titulo de la informacion y el texto

**Comment by jairdean** [comment]
en index poner titulo a lo que dice "LO MAS NUEVO", ponerle en el centro y ver si este titulo y el de puja "TERMINA EN " se los cambia a otro color que se distinga de la pagina que ya es verde.

**Comment by jairdean** [comment]
necesitamos poner ya sea en el index o en el header "QUIENES SOMOS", "CONTACTOS", "DIRECCION MAPA"

**Comment by jairdean** [comment]
AHORA EN LA PAGINA ADMIN moneda; existe monedas que YA NO SE PUEDE eliminar porque ya son parte de un trueque y por ende NUNCA se las podra eliminar, ver si se valida eso........ dejo a votacion.

**Comment by jairdean** [comment]
en el indice el "SUBTITULO DE CADA trueque" se le puede cambiar por algo similar a lo que JAIRO tiene en usuario personal. un box azul..... favor preguntar a Jairo.

**Comment by jairdean** [comment]
al desplegar el combobox de categorias en ingresar trueque debe hacerlo por orden ALFABETICO de la A-Z desc

**Comment by jairdean** [comment]
revisar el hitorico que despliega JAIRIN y controlarco con las hitorias que ingresa el macho del
 Jonathan

**Comment by jairdean** [comment]
Incluir mensajes a los usuarios MAILS AUTOMATICOS en las pujas

**Comment by jairdean** [comment]
controlar la session en los JSP en pujas

**Comment by jairdean** [comment]
revisar en todos los jsp ique tengan titulo "INSERT TITLE HERE"

**Comment by jairdean** [comment]
JONATHAN debe cerrar las conexiones y los resultset, tambien las conexiones debe meterlas antes de cada try y catch, PARA CERRAR LAS conexiones y el resultset debe crear UN NUEVO TRY y CATCH donde va lo siguiente try {
            resultSet.close();
            con.getConexion().close();
        } catch (Exception e) {
            // TODO: handle exception
        }

**Comment by jairdean** [comment]
orden alfabetico de las categorias en puja

**Comment by jairdean** [comment]
poner el boton de subir puja al centro y darle un <br> para que se separe del fin de la pagina.
